 
  version: '3'
  
  
  services:
    zumbach_bk:
      # image: node
      container_name: Zumbach_BK
      ports:
        - "3001:3000"
      build:  .
      command: npm run start:dev
      volumes:
        - zumdb_photos: ./static
    db:
      image:  postgres:15.2
      restart:  always
      ports:
        - "5432:5432"
      environment:
        POSTGRES_PASSWORD:  ${DB_PASSWORD}
        POSTGRES_DB:  ${DB_NAME}
      container_name: ${DB_HOST}
      volumes:
        - zumdb_postgres:/var/lib/posgresql/data
  volumes:
    zumdb_postgres:
      external: true
    zumdb_photos:
      external: true
    
        



    